//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> PostNumber { get; set; }
        public System.DateTime PublicationStart { get; set; }
        public Nullable<System.DateTime> ContractStart { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
        public bool Inspect { get; set; }
        public long IdProducer { get; set; }
        public long IdContractType { get; set; }
        public long IdJob { get; set; }
    
        public virtual ContractType ContractType { get; set; }
        public virtual Job Job { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
